sudo: false
language: python
python:
  - "3.3"
  - "3.4"
  - "nightly"
matrix:
  allow_failures:
    - python: "nightly"
cache: pip
script: cp config_example.ini config.ini; python -m unittest discover tests
